// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type Bot struct {
	ID          int64
	Author      int64
	Name        string
	Description sql.NullString
	CreatedAt   time.Time
}

type User struct {
	ID        int64
	Username  string
	CreatedAt time.Time
}
