// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type Bot struct {
	ID          string
	Author      string
	Name        string
	Description sql.NullString
	CreatedAt   time.Time
}

type User struct {
	ID        string
	Username  string
	CreatedAt time.Time
}
